### ISSUE TITLE
node_object_wrap.h:71 error

### ISSUE THREAD

**Issue by mingfai** [ksperis/node-rados#10]
any idea what may cause the following error?
```
> cluster = rados.Rados('ceph','client.admin','/etc/ceph/ceph.conf')
nodejs: /usr/include/nodejs/src/node_object_wrap.h:71: void node::ObjectWrap::Wrap(v8::Handle<v8::Object>): Assertion `handle->InternalFieldCount() > 0' failed.
```
nodejs v0.10.25

**Comment by siboulet** [comment]
You are not instantiating the Rados object ie. you are missing the "new" statement (new rados.Rados()).

The module should probably fail more gracefully when not being properly instantiated.

**Comment by mingfai** [comment]
thx and sorry for the stupid question :-P

**Comment by ksperis** [comment]
Thank you Simon. You're right, I added more explicit error for this case :
https://github.com/ksperis/node-rados/commit/d3d8c5bfe99c9ae965e566a2dfc6b34fc4c825db
