### ISSUE TITLE
Manage pool

### ISSUE THREAD

**Issue by wcc21320** [ksperis/node-rados#11]
Hi,  thanks for you create this and its helpful!
I know there's function to manage pools in python. But seems not support here.
Would you please add manage pool functions?

**Comment by siboulet** [comment]
Hi,

http://ceph.com/docs/master/rados/api/python/#manage-pools

I suppose you'd like to see the create_pool and delete_pool methods? We already have the pool_list() method (list_pools in the Python bindings).

**Comment by ksperis** [comment]
I just add pool_create () and pool_delete (). To be tested ...

**Comment by wcc21320** [comment]
That's great, thank you!

**Comment by wcc21320** [comment]
Hi, I try 'npm install rados' to update the module but the latest code seems not involved. And then I try to clone the module from web and run 'npm install nan; node-gyp rebuild'; then I could see the code in rasod.h has updated, but as I call 'cluster.create_pool('test_pool');', and I got :

Object #<Rados> has no method 'create_pool'

Could you please help about this? or any suggestion to check?

**Comment by ksperis** [comment]
Hi,
I updated the npm package with new functions.

Laurent

**Comment by wcc21320** [comment]
Hi, it works fine, thanks a lot!
