### ISSUE TITLE
Connect to docker/ceph

### ISSUE THREAD

**Issue by wcc21320** [ksperis/node-rados#15]
Hi, I got a docker/ceph cluster and it's "ceph.conf" is strange as below, and seems I can not connect to it through node-rados:

fsid = f9be0dfe-f839-4ebd-9c1b-ccabf96a1bef
mon initial members = mon_0
mon host = 192.168.23.130
auth cluster required = cephx
auth service required = cephx
auth client required = cephx

Any suggestions?

**Comment by siboulet** [comment]
That ceph.conf configuration look pretty simple. How are you connecting (code) and what error are you getting? Did you try the ceph command line tool, are you having problems with these too?

**Comment by wcc21320** [comment]
1. How ~ connecting:
    The cluster (docker/ceph) is built on 192.168.23.130, and my node-rados is running on another machine. (My node-rados can connect to other normal way built ceph cluster on other IP successfully with their "ceph.conf" file)
    I use the connecting method of sample code : 
var err = cluster.connect();
    And only got the return code (err) with value 2. 

2. What error I got is error code : 2 

3. Ceph command line tool : I don't know how to connect ceph cluster remotely in my case. I can do this (ceph command line tool) in that target 192.168.23.130, and "chep -s" show its health is ok. I can add pool and put object correctlly.

**Comment by ksperis** [comment]
Hi,
The error code 2 should be a "no such file".
Could you verify that you have the rights to read the file /etc/ceph/ceph.client.admin.keyring ?

**Comment by wcchh** [comment]
It works! Thank you very mush!
So we need two files to build the connection: "ceph.conf" and "ceph.client.admin.keyring".
