### ISSUE TITLE
Drop node-gyp dependency

### ISSUE THREAD

**Issue by kpcyrd** [ksperis/node-rados#19]
hello,

I'm interested in adding rados as a dependency to my project, but it's dependency list is significant due to node-gyp, which, as far as I know, isn't required. (see [scrypt](https://www.npmjs.com/package/scrypt)).

Could you please drop this dependency?

**Comment by ksperis** [comment]
You're right, this dependence could be removed. Node-gyp need to be globally installed.
I removed it here : 7aeb999d3d7b81e2230baccfebec63e4490fcbfe
Thanks
